api:
  mode: debug
  port: 8080
database:
  driver: postgres
  host: 172.16.7.134
  maxactive: 10
  maxidle: 10
  maxidletime: 60
  maxlifetime: 60
  name: theta_cloud
  password: "123456"
  port: 5432
  username: postgres
iot:
  broker: 127.0.0.1:1883
  password: "123456"
  server:
    enabled: true
    port: 1883
  username: admin
socket:
  port: 8081
