api:
  port: 8080
  mode: "debug"

socket:
  port: 8081

mqtt:
  username: "admin"
  password: "123456"
  server:
    port: 1883
    enabled: true
  client:
    broker: "localhost:1883"

database:
  driver: "postgres"
  host: "172.16.7.134"
  port: 5432
  username: "postgres"
  password: "123456"
  name: "theta_cloud"
  maxIdle: 10
  maxIdleTime: 60
  maxActive: 10
  maxLifetime: 60

