import { PROPERTY_CATEGORIES } from '../../../constants/properties';

export enum MonitoringPointTypeValue {
  LOOSENING_ANGLE = 10101,
  THICKNESS = 10201,
  THICKNESS_HIGH = 10202,
  PRELOAD = 10301,
  VIBRATION = 10401,
  PRESSURE = 10601,
  PRESSURE_TEMPERATURE = 10602,
  FLANGE_PRELOAD = 10311,
  TEMPERATURE = 10801,
  TOWER_INCLINATION = 10511,
  TOWER_BASE_SETTLEMENT = 10512,
  PRELOAD_ATTITUDE = 10303,
  VIBRATION_RPM = 10402,
  VIBRATION_THREE_AXIS_RPM = 10403
}

export enum MonitoringPointTypeText {
  LOOSENING_ANGLE = 'FIELD_LOOSENING_ANGLE',
  THICKNESS = 'FIELD_THICKNESS',
  THICKNESS_HIGH = 'FIELD_THICKNESS_HIGH',
  PRELOAD = 'SETTING_GROUP_PRELOAD',
  VIBRATION = 'VIBRATION',
  PRESSURE = 'FIELD_PRESSURE2',
  PRESSURE_TEMPERATURE = 'DEVICE_TYPE_PRESSURE_TEMPERATURE',
  FLANGE_PRELOAD = 'FLANGE_PRELOAD',
  TEMPERATURE = 'FIELD_TEMPERATURE',
  TOWER_INCLINATION = 'TOWER_INCLINATION',
  TOWER_BASE_SETTLEMENT = 'TOWER_BASE_SETTLEMENT',
  PRELOAD_ATTITUDE = 'PRELOAD_ATTITUDE',
  VIBRATION_RPM = 'VIBRATION_RPM',
  VIBRATION_THREE_AXIS_RPM = 'VIBRATION_THREE_AXIS_RPM'
}

export const MONITORING_POINT_DISPLAY_PROPERTIES = {
  [MonitoringPointTypeValue.LOOSENING_ANGLE]: PROPERTY_CATEGORIES.SA,
  [MonitoringPointTypeValue.PRELOAD]: PROPERTY_CATEGORIES.SAS,
  [MonitoringPointTypeValue.FLANGE_PRELOAD]: PROPERTY_CATEGORIES.SAS,
  [MonitoringPointTypeValue.PRELOAD_ATTITUDE]: PROPERTY_CATEGORIES.SAS,
  [MonitoringPointTypeValue.THICKNESS]: PROPERTY_CATEGORIES.DC_NORMAL,
  [MonitoringPointTypeValue.THICKNESS_HIGH]: PROPERTY_CATEGORIES.DC_NORMAL,
  [MonitoringPointTypeValue.VIBRATION]: PROPERTY_CATEGORIES.SVT210R,
  [MonitoringPointTypeValue.VIBRATION_RPM]: PROPERTY_CATEGORIES.SVT220S1S3,
  [MonitoringPointTypeValue.VIBRATION_THREE_AXIS_RPM]: PROPERTY_CATEGORIES.SVT220S1S3,
  [MonitoringPointTypeValue.TOWER_INCLINATION]: PROPERTY_CATEGORIES.TOWER_INCLINATION,
  [MonitoringPointTypeValue.TOWER_BASE_SETTLEMENT]: PROPERTY_CATEGORIES.TOWER_BASE_SETTLEMENT,
  [MonitoringPointTypeValue.TEMPERATURE]: PROPERTY_CATEGORIES.ST,
  [MonitoringPointTypeValue.PRESSURE_TEMPERATURE]: PROPERTY_CATEGORIES.SPT
};

export const MONITORING_POINT = 'MONITORING_POINT';
export const MONITORING_POINT_LIST = `MONITORING_POINT_LIST`;
export const INVALID_MONITORING_POINT = `ABNORMAL_MONITORING_POINT`;
